config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :items, only: [:index, :show], param: :slug
  resources :merchants, only: [:index]

  get '/cart', to: 'cart#index'
  post '/cart/additem/:slug', to: 'cart#add_item', as: 'cart_add_item'
  post '/cart/addmoreitem/:slug', to: 'cart#add_more_item', as: 'cart_add_more_item'
  delete '/cart', to: 'cart#destroy', as: 'cart_empty'
  delete '/cart/item/:slug', to: 'cart#remove_more_item', as: 'cart_remove_more_item'
  delete '/cart/item/:slug/all', to: 'cart#remove_all_of_item', as: 'cart_remove_item_all'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'

  get '/register', to: 'users#new', as: 'registration'
  resources :users, only: [:create, :update], param: :slug

  get '/dashboard', to: 'merchants#show', as: 'dashboard'
  namespace :dashboard do
    resources :orders, only: [:show] do
      patch '/items/:slug/fulfill', to: 'orders#fulfill_item', as: 'item_fulfill'
    end
    resources :items, except: [:show], param: :slug
    patch '/items/:slug/enable', to: 'items#enable', as: 'enable_item'
    patch '/items/:slug/disable', to: 'items#disable', as: 'disable_item'
  end
  get '/profile', to: 'profile#index', as: 'profile'

  get '/profile/edit', to: 'users#edit'
  namespace :profile do
    resources :orders, only: [:index, :create, :show, :destroy]
  end

  get '/admin/users/:merchant_slug/items', to: 'admin/items#index', as: 'admin_merchant_items', param: :slug
  post '/admin/users/:merchant_id/items', to: 'dashboard/items#create', as: 'admin_user_items'
  patch '/admin/users/:merchant_id/items/:slug', to: 'dashboard/items#update', as: 'admin_user_item'
  namespace :admin do
    resources :users, only: [:index, :show, :edit], param: :slug do
      patch '/enable', to: 'users#enable', as: 'enable'
      patch '/disable', to: 'users#disable', as: 'disable'
      patch '/upgrade', to: 'users#upgrade', as: 'upgrade'
      resources :orders, only: [:index, :show]
    end
    resources :merchants, only: [:show], param: :slug do
      patch '/enable', to: 'merchants#enable', as: 'enable'
      patch '/disable', to: 'merchants#disable', as: 'disable'
      patch '/upgrade', to: 'merchants#downgrade', as: 'downgrade'
      resources :items, only: [:new, :edit], param: :slug
    end
    resources :dashboard, only: [:index]
  end
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || Hash.new(0)
  end

  def total_count
    @contents.values.sum
  end

  def count_of(item_id)
    @contents[item_id.to_s].to_i
  end

  def add_item(item_id)
    @contents[item_id.to_s] ||= 0
    @contents[item_id.to_s] += 1
  end

  def subtract_item(item_id)
    @contents[item_id.to_s] -= 1
    @contents.delete(item_id.to_s) if @contents[item_id.to_s] == 0
  end

  def remove_all_of_item(item_id)
    @contents.delete(item_id.to_s)
  end

  def items
    @contents.keys.map do |item_id|
      Item.includes(:user).find(item_id)
    end
  end

  def subtotal(item_id)
    item = Item.find(item_id)
    item.price * count_of(item_id)
  end

  def grand_total
    @contents.keys.map do |item_id|
      subtotal(item_id)
    end.sum
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include ActionView::Helpers::TextHelper

  before_action :require_default_user_or_visitor

  def index
    @items = @cart.items
  end

  def add_item
    add_item_to_cart(params[:id])
    redirect_to items_path
  end

  def add_more_item
    add_item_to_cart(params[:id])
    redirect_to cart_path
  end

  def remove_more_item
    item = Item.find_by(slug: params[:slug])
    @cart.subtract_item(item.id)
    flash[:success] = "You have removed 1 package of #{item.name} from your cart, new quantity is #{@cart.count_of(item.id)}"
    session[:cart] = @cart.contents
    redirect_to cart_path
  end

  def remove_all_of_item
    item = Item.find_by(slug: params[:slug])
    @cart.remove_all_of_item(item.id)
    flash[:success] = "You have removed all packages of #{item.name} from your cart"
    session[:cart] = @cart.contents
    redirect_to cart_path
  end

  def destroy
    session[:cart] = nil
    @cart = Cart.new(session[:cart])
    redirect_to cart_path
  end

  private

  def require_default_user_or_visitor
    render file: 'errors/not_found', status: 404 unless !current_user || (current_user && current_user.default?)
  end

  def add_item_to_cart(item_id)
    item = Item.find_by(slug: params[:slug])
    @cart.add_item(item.id)
    flash[:success] = "You have #{pluralize(@cart.count_of(item.id), 'package')} of #{item.name} in your cart"
    session[:cart] = @cart.contents
  end
end

app/views/cart/_cart_item.html.erb
<div class="card float-left m-3" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= link_to item.name, item_path(item) %></h5>
    <img id="item-<%= item.id %>-image" alt="image for <%= item.name %>" src="<%= item.image %>" width="<%= img_width %>" />
    <p>Merchant: <%= item.user.name %></p>
    <p>Price: <%= number_to_currency(item.price) %></p>
    <p>Quantity: <%= @cart.count_of(item.id) %> of <%= item.inventory %> available</p>
    <p>Subtotal: <%= number_to_currency(@cart.subtotal(item.id)) %></p>
    <p>
    <% if @cart.count_of(item.id) < item.inventory %>
    <%= button_to 'Add more to cart', cart_add_more_item_path(item) %>
    <% end %>
    <%= button_to 'Remove one from cart', cart_remove_more_item_path(item), method: :delete %>
    <%= button_to 'Remove all from cart', cart_remove_item_all_path(item), method: :delete %>
    </p>
  </div>
</div>

app/views/cart/index.html.erb
<% if @cart.contents.empty? %>
  <p>Your cart is empty</p>
<% else %>
  Total: <%= number_to_currency(@cart.grand_total) %>

  <%= button_to "Empty cart", cart_empty_path, method: :delete %>

  <% if current_user %>
    <%= button_to 'Check out', profile_orders_path %>
  <% else %>
    You must
    <%= link_to 'register', registration_path %>
    or
    <%= link_to 'log in', login_path %>
    to check out.
  <% end %>

  <% @items.each do |item| %>
    <%= tag.div id: "item-#{item.id}" do %>
      <%= render partial: "cart_item", locals: {item: item, img_width: 150} %>
    <% end %>
  <% end %>
<% end %>