config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :items, only: [:index, :show], param: :slug
  resources :merchants, only: [:index]

  get '/cart', to: 'cart#index'
  post '/cart/additem/:slug', to: 'cart#add_item', as: 'cart_add_item'
  post '/cart/addmoreitem/:slug', to: 'cart#add_more_item', as: 'cart_add_more_item'
  delete '/cart', to: 'cart#destroy', as: 'cart_empty'
  delete '/cart/item/:slug', to: 'cart#remove_more_item', as: 'cart_remove_more_item'
  delete '/cart/item/:slug/all', to: 'cart#remove_all_of_item', as: 'cart_remove_item_all'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'

  get '/register', to: 'users#new', as: 'registration'
  resources :users, only: [:create, :update], param: :slug

  get '/dashboard', to: 'merchants#show', as: 'dashboard'
  namespace :dashboard do
    resources :orders, only: [:show] do
      patch '/items/:slug/fulfill', to: 'orders#fulfill_item', as: 'item_fulfill'
    end
    resources :items, except: [:show], param: :slug
    patch '/items/:slug/enable', to: 'items#enable', as: 'enable_item'
    patch '/items/:slug/disable', to: 'items#disable', as: 'disable_item'
  end
  get '/profile', to: 'profile#index', as: 'profile'

  get '/profile/edit', to: 'users#edit'
  namespace :profile do
    resources :orders, only: [:index, :create, :show, :destroy]
  end

  get '/admin/users/:merchant_slug/items', to: 'admin/items#index', as: 'admin_merchant_items', param: :slug
  post '/admin/users/:merchant_id/items', to: 'dashboard/items#create', as: 'admin_user_items'
  patch '/admin/users/:merchant_id/items/:slug', to: 'dashboard/items#update', as: 'admin_user_item'
  namespace :admin do
    resources :users, only: [:index, :show, :edit], param: :slug do
      patch '/enable', to: 'users#enable', as: 'enable'
      patch '/disable', to: 'users#disable', as: 'disable'
      patch '/upgrade', to: 'users#upgrade', as: 'upgrade'
      resources :orders, only: [:index, :show]
    end
    resources :merchants, only: [:show], param: :slug do
      patch '/enable', to: 'merchants#enable', as: 'enable'
      patch '/disable', to: 'merchants#disable', as: 'disable'
      patch '/upgrade', to: 'merchants#downgrade', as: 'downgrade'
      resources :items, only: [:new, :edit], param: :slug
    end
    resources :dashboard, only: [:index]
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, foreign_key: 'merchant_id'
  has_many :order_items
  has_many :orders, through: :order_items

  validates_presence_of :name, :description
  validates :slug, presence: true, uniqueness: true
  validates :price, presence: true, numericality: {
    only_integer: false,
    greater_than_or_equal_to: 0
  }
  validates :inventory, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }

  def self.item_popularity(count, order)
    Item.joins(:order_items)
      .select("items.*, sum(order_items.quantity) as total_ordered")
      .order("total_ordered #{order}")
      .group(:id)
      .limit(count)
  end

  def self.popular_items(count)
    item_popularity(count, :desc)
  end

  def self.unpopular_items(count)
    item_popularity(count, :asc)
  end

  def avg_fulfillment_time
    results = ActiveRecord::Base.connection.execute("select avg(updated_at - created_at) as avg_f_time from order_items where item_id=#{self.id} and fulfilled='t'")
    if results.present?
      return results.first['avg_f_time']
    else
      return nil
    end
  end

  def ever_ordered?
    OrderItem.find_by_item_id(self.id) !=  nil
  end

  def to_param
    slug
  end

  def slug_check(slug)
    if Item.where(slug: slug).exists?
      slug = "#{slug}-#{(Item.where("slug LIKE ?", "%#{slug}%").count + 1)}"
    end
    slug
  end

  def generate_slug
    slug = "#{ name.downcase.parameterize }" if name
    self.slug = slug_check(slug) if name
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  def index
    @merchant = User.find_by(slug: params[:merchant_slug])
    @items = @merchant.items
    render '/dashboard/items/index'
  end

  def new
    @merchant = User.find_by(slug: params[:merchant_slug])
    @item = Item.new
    @form_path = [:admin, @merchant, @item]
    render "/dashboard/items/new"
  end

  def edit
    @merchant = User.find_by(slug: params[:merchant_slug])
    @item = Item.find_by(slug: params[:slug])
    @form_path = [:admin, @merchant, @item]
    render "/dashboard/items/edit"
  end

end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_action :restrict_access

  def restrict_access
    render file: 'errors/not_found', status: 404 unless current_user && (current_merchant? || current_admin?)
  end
end

app/controllers/dashboard/items_controller.rb
class Dashboard::ItemsController < Dashboard::BaseController
  def index
    merchant = current_user
    @items = merchant.items.order(:name)
  end

  def new
    @item = Item.new
    @form_path = [:dashboard, @item]
  end

  def edit
    @item = Item.find_by(slug: params[:slug])
    @form_path = [:dashboard, @item]
  end

  def create
    ip = item_params
    if ip[:image].empty?
      ip[:image] = 'https://picsum.photos/200/300/?image=524'
    end
    ip[:active] = true
    @merchant = current_user
    if current_admin?
      @merchant = User.find_by(slug: params[:merchant_id])
    end
    @item = @merchant.items.create(ip)
    @item.generate_slug
    if @item.save
      flash[:success] = "#{@item.name} has been added!"
      if current_admin?
        redirect_to admin_merchant_items_path(@merchant)
      else
        redirect_to dashboard_items_path
      end
    else
      if current_admin?
        @form_path = [:admin, @merchant, @item]
      else
        @form_path = [:dashboard, @item]
      end
      render :new
    end
  end

  def destroy
    @item = Item.find_by(slug: params[:slug])
    merchant = @item.user
    if @item && @item.ever_ordered?
      flash[:error] = "Attempt to delete #{@item.name} was thwarted!"
    elsif @item
      @item.destroy
    end
    if current_admin?
      redirect_to admin_merchant_items_path(merchant)
    else
      redirect_to dashboard_items_path
    end
  end
  
  def update
    @merchant = current_user
    if current_admin?
      @merchant = User.find_by(slug: params[:merchant_id])
    end
    
    @item = Item.find_by(slug: params[:slug])

    ip = item_params
    if ip[:image].empty?
      ip[:image] = 'https://picsum.photos/200/300/?image=524'
    end
    ip[:active] = true
    if ip[:name] != @item.name && ip[:name] != ""
      @item.update(ip)
      @item.generate_slug
    else
      @item.update(ip)
    end
    if @item.save
      flash[:success] = "#{@item.name} has been updated!"
      if current_admin?
        redirect_to admin_merchant_items_path(@merchant)
      else
        redirect_to dashboard_items_path
      end
    else
      if current_admin?
        @form_path = [:admin, @merchant, @item]
      else
        @form_path = [:dashboard, @item]
      end
      render :edit
    end
  end

  def enable
    set_item_active(true)
  end

  def disable
    set_item_active(false)
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :image, :price, :inventory)
  end

  def set_item_active(state)
    item = Item.find_by(slug: params[:slug])
    item.active = state
    item.save
    if current_admin?
      redirect_to admin_merchant_items_path(item.user)
    else
      redirect_to dashboard_items_path
    end
  end

end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < Dashboard::BaseController
  def show
    @order = Order.find(params[:id])
    @items = @order.my_items(current_user)
  end

  def fulfill_item
    order = Order.find(params[:order_id])
    item = Item.find_by(slug: params[:slug])
    oi = order.order_items.find_by(item_id: item.id)
    if oi
      oi.fulfilled = true
      oi.save
      item.inventory -= oi.quantity
      item.save
    end
    if order.order_items.where(fulfilled: false).empty?
      order.status = :completed
      order.save
    end
    redirect_to dashboard_order_path(order)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.where(active: true)
    @popular_items = Item.popular_items(5)
    @unpopular_items = Item.unpopular_items(5)
  end

  def show
    @item = Item.find_by(slug: params[:slug])
  end
end

app/views/dashboard/items/_form.html.erb
<%= form_for @form_path do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p><%= f.label :name %>
<%= f.text_field :name, required: true %></p>

<p><%= f.label :description %>
<%= f.text_area :description, required: true %></p>

<p><%= f.label :image %>
<%= f.text_field :image %></p>

<p><%= f.label :price %>
<%= f.number_field :price, min: 0.01, step: :any %></p>

<p><%= f.label :inventory %>
<%= f.number_field :inventory, min: 0 %></p>

<p><%= f.submit %></p>
<% end %>

app/views/dashboard/items/_item_card.html.erb
<div class="card float-left m-3" style="width: 18rem;">
  <div class="card-body">

<p>ID: <%= item.id %></p>
<p>Name: <%= link_to item.name, item_path(item) %></p>
<a href="<%= item_path(item) %>">
<img id="item-<%= item.id %>-image" alt="image for <%= item.name %>" src="<%= item.image %>" width="<%= img_width %>" />
</a>
<p>Price: <%= number_to_currency(item.price) %></p>
<p>Inventory: <%= item.inventory %></p>
<p>
<% if current_admin? %>
<%= link_to 'Edit Item', edit_admin_merchant_item_path(@merchant, item) %>
<% else %>
<%= link_to 'Edit Item', edit_dashboard_item_path(item) %>
<% end %>
</p>

<p><% if item.active %>
<%= button_to 'Disable Item', dashboard_disable_item_path(item), method: :patch %>
<% else %>
<%= button_to 'Enable Item', dashboard_enable_item_path(item), method: :patch %>
<% end %>
<% unless item.ever_ordered? %>
<%= button_to 'Delete Item', dashboard_item_path(item), method: :delete %>
<% end %>
</p>

</div>
</div>

app/views/dashboard/items/edit.html.erb
<h2>Edit Item</h2>

<%= render '/dashboard/items/form' %>

app/views/dashboard/items/index.html.erb
<h2>My Items for Sale</h2>

<% if current_admin? %>
<%= link_to 'Add new Item', new_admin_merchant_item_path(@merchant) %>
<% else %>
<%= link_to 'Add new Item', new_dashboard_item_path %>
<% end %>

<% @items.each do |item| %>
  <%= tag.div id: "item-#{item.id}" do %>
  <%= render partial: "/dashboard/items/item_card", locals: {item: item, img_width: 200} %>
  <% end %>
<% end %>

app/views/dashboard/items/new.html.erb
<h2>New Item</h2>

<%= render '/dashboard/items/form' %>