config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :items, only: [:index, :show], param: :slug
  resources :merchants, only: [:index]

  get '/cart', to: 'cart#index'
  post '/cart/additem/:slug', to: 'cart#add_item', as: 'cart_add_item'
  post '/cart/addmoreitem/:slug', to: 'cart#add_more_item', as: 'cart_add_more_item'
  delete '/cart', to: 'cart#destroy', as: 'cart_empty'
  delete '/cart/item/:slug', to: 'cart#remove_more_item', as: 'cart_remove_more_item'
  delete '/cart/item/:slug/all', to: 'cart#remove_all_of_item', as: 'cart_remove_item_all'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'

  get '/register', to: 'users#new', as: 'registration'
  resources :users, only: [:create, :update], param: :slug

  get '/dashboard', to: 'merchants#show', as: 'dashboard'
  namespace :dashboard do
    resources :orders, only: [:show] do
      patch '/items/:slug/fulfill', to: 'orders#fulfill_item', as: 'item_fulfill'
    end
    resources :items, except: [:show], param: :slug
    patch '/items/:slug/enable', to: 'items#enable', as: 'enable_item'
    patch '/items/:slug/disable', to: 'items#disable', as: 'disable_item'
  end
  get '/profile', to: 'profile#index', as: 'profile'

  get '/profile/edit', to: 'users#edit'
  namespace :profile do
    resources :orders, only: [:index, :create, :show, :destroy]
  end

  get '/admin/users/:merchant_slug/items', to: 'admin/items#index', as: 'admin_merchant_items', param: :slug
  post '/admin/users/:merchant_id/items', to: 'dashboard/items#create', as: 'admin_user_items'
  patch '/admin/users/:merchant_id/items/:slug', to: 'dashboard/items#update', as: 'admin_user_item'
  namespace :admin do
    resources :users, only: [:index, :show, :edit], param: :slug do
      patch '/enable', to: 'users#enable', as: 'enable'
      patch '/disable', to: 'users#disable', as: 'disable'
      patch '/upgrade', to: 'users#upgrade', as: 'upgrade'
      resources :orders, only: [:index, :show]
    end
    resources :merchants, only: [:show], param: :slug do
      patch '/enable', to: 'merchants#enable', as: 'enable'
      patch '/disable', to: 'merchants#disable', as: 'disable'
      patch '/upgrade', to: 'merchants#downgrade', as: 'downgrade'
      resources :items, only: [:new, :edit], param: :slug
    end
    resources :dashboard, only: [:index]
  end
end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::BaseController
  def show
    @merchant = User.find_by(slug: params[:slug])
    if @merchant.default?
      redirect_to admin_user_path(@merchant)
    else
      @orders = @merchant.my_pending_orders
      @orders = @merchant.my_pending_orders
      @top_5_items = @merchant.top_items_by_quantity(5)
      @qsp = @merchant.quantity_sold_percentage
      @top_3_states = @merchant.top_3_states
      @top_3_cities = @merchant.top_3_cities
      @most_ordering_user = @merchant.most_ordering_user
      @most_items_user = @merchant.most_items_user
      @most_items_user = @merchant.most_items_user
      @top_3_revenue_users = @merchant.top_3_revenue_users
      @monthly_sales = @merchant.monthly_sales
      render :'merchants/show'
    end
  end

  def enable
    set_user_active(true)
  end

  def disable
    set_user_active(false)
  end

  def downgrade
    set_user_role(User.find_by(slug: params[:merchant_slug]), :default)
    redirect_to merchants_path
  end

  private

  def set_user_active(state)
    user = User.find_by(slug: params[:merchant_slug])
    user.active = state
    user.save
    redirect_to merchants_path
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :require_merchant, only: :show

  def index
    flags = {role: :merchant}
    unless current_admin?
      flags[:active] = true
    end
    @merchants = User.where(flags)

    @top_3_revenue_merchants = User.top_3_revenue_merchants
    @top_3_fulfilling_merchants = User.top_3_fulfilling_merchants
    @bottom_3_fulfilling_merchants = User.bottom_3_fulfilling_merchants
    @top_3_states = Order.top_3_states
    @top_3_cities = Order.top_3_cities
    @top_3_quantity_orders = Order.top_3_quantity_orders
    @total_sales = User.total_sold
  end

  def show
    @merchant = current_user
    @orders = @merchant.my_pending_orders
    @top_5_items = @merchant.top_items_by_quantity(5)
    @qsp = @merchant.quantity_sold_percentage
    @top_3_states = @merchant.top_3_states
    @top_3_cities = @merchant.top_3_cities
    @most_ordering_user = @merchant.most_ordering_user
    @most_items_user = @merchant.most_items_user
    @most_items_user = @merchant.most_items_user
    @top_3_revenue_users = @merchant.top_3_revenue_users
    @monthly_sales = @merchant.monthly_sales
  end

  private

  def require_merchant
    render file: 'errors/not_found', status: 404 unless current_user && current_merchant?
  end
end

app/views/merchants/_bar_chart.html.erb
<canvas id="myChart" width="400" height="400"></canvas>
<script>
  const bar_ctx = document.getElementById("myChart");
  const monthly_data = <%=  raw chart_data.to_json %>
  const myChart = new Chart(bar_ctx, {
      type: 'bar',
      data: {
          labels: [
            "January", 
            "Febuary", 
            "March", 
            "April", 
            "May", 
            "June", 
            "July", 
            "August", 
            "September", 
            "October", 
            "November", 
            "December"
          ],
          datasets: [{
              label: '# of Sales',
              data: monthly_data,
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(255, 99, 132, 0.2)',
              ],
              borderColor: [
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
                  'rgba(255,99,132,1)',
              ],
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero:true
                  }
              }]
          }
      }
  });
</script>

app/views/merchants/_order_card.html.erb
<p><%= link_to "Order ID #{order.id}", dashboard_order_path(order) %></p>
<p>Created: <%= order.created_at %></p>
<p>Items in Order: <%= order.my_item_count(@merchant.id) %></p>
<p>Value of Order: <%= number_to_currency(order.my_revenue_value(@merchant.id)) %></p>

app/views/merchants/_pie_chart.html.erb
<canvas id="pie-chart" height="10vh" width="10vw"></canvas>
<script>
  const qsp_data = <%=  raw qsp_data.to_json %>
  const total_data = <%=  raw total_data.to_json %>
  const qsp = [qsp_data.sold, (qsp_data.total - qsp_data.sold)]
  const tas = total_data.map(user => user.amount_sold)
  const qsp_labels = ['Sold', 'Unsold']
  const tas_labels = total_data.map(user => user.name)
  const avalible_data = qsp_data.sold ? qsp : tas
  const labels = qsp_data === {} ? qsp_labels : tas_labels
  const ctx = document.getElementById("pie-chart").getContext('2d');
  
  const data = {
    datasets: [{
        data: avalible_data,            
        backgroundColor: [
          'rgba(54, 162, 235, 0.2)',
          'rgba(255, 99, 132, 0.2)',
          'rgba(255, 206, 86, 0.2)',
          'rgba(75, 192, 192, 0.2)',
          'rgba(153, 102, 255, 0.2)',
          'rgba(255, 159, 64, 0.2)'
        ],
        borderColor: [
          'rgba(54, 162, 235, 1)',
          'rgba(255,99,132,1)',
          'rgba(255, 206, 86, 1)',
          'rgba(75, 192, 192, 1)',
          'rgba(153, 102, 255, 1)',
          'rgba(255, 159, 64, 1)'
        ],
        borderWidth: 1
    }],
    labels: labels
  };

  const myPieChart = new Chart(ctx,{
      type: 'pie',
      data: data
  });
</script>

app/views/merchants/index.html.erb
<h2>Merchants</h2>

<table>
  <thead>
    <tr>
      <th>Name, Location</th>
      <th>Registration</th>
      <% if current_admin? %>
      <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
<% @merchants.each do |merchant| %>
  <%= tag.tr id: "merchant-#{merchant.id}" do %>
  <td>
    <% if current_admin? %><%= link_to merchant.name, admin_merchant_path(merchant) %><% else %><%= merchant.name %><% end %>,
    <%= merchant.city %> <%= merchant.state %></td>
  <td>Registered: <%= merchant.created_at %></td>
  <% if current_admin? %>
  <td>
      <% if merchant.active? %>
      <%= button_to 'Disable', admin_merchant_disable_path(merchant), method: :patch %>
      <% else %>
      <%= button_to 'Enable', admin_merchant_enable_path(merchant), method: :patch %>
      <% end %>
    <% end %>
  </td>
  <% end %>
<% end %>

</tbody>
</table>

<hr>

<%= tag.div id: "statistics" do %>
  <%= tag.div id: "top-3-revenue-merchants" do %>
    <h4>Top 3 Merchants by Revenue</h4>
    <ol>
    <% @top_3_revenue_merchants.each do |merchant| %>
    <%= tag.li class: 'merchant' do %>
    <%= merchant.name %>, Revenue: <%= number_to_currency(merchant.revenue) %>
    <% end %>
    <% end unless @top_3_revenue_merchants.nil? %>
    </ol>
  <% end %>

  <%= tag.div id: "top-3-fulfilling-merchants" do %>
    <h4>Top 3 Fastest Fulfilling Merchants</h4>
    <ol>
    <% @top_3_fulfilling_merchants.each do |merchant| %>
    <%= tag.li class: 'merchant' do %>
    <%= merchant.name %>, Average Fulfillment Time: <%= fulfillment_time(merchant.avg_fulfillment_time) %>
    <% end %>
    <% end unless @top_3_fulfilling_merchants.nil? %>
    </ol>
  <% end %>

  <%= tag.div id: "bottom-3-fulfilling-merchants" do %>
    <h4>Top 3 Slowest Fulfilling Merchants</h4>
    <ol>
    <% @bottom_3_fulfilling_merchants.each do |merchant| %>
    <%= tag.li class: 'merchant' do %>
    <%= merchant.name %>, Average Fulfillment Time: <%= fulfillment_time(merchant.avg_fulfillment_time) %>
    <% end %>
    <% end unless @bottom_3_fulfilling_merchants.nil? %>
    </ol>
  <% end %>

  <%= tag.div id: "top-3-states-shipped" do %>
    <h4>Top 3 States where Orders Ship</h4>
    <ol>
    <% @top_3_states.each do |order| %>
    <%= tag.li class: 'state' do %>
    <%= order.state %>, <%= pluralize(order.order_count, 'order') %>
    <% end %>
    <% end unless @top_3_states.nil? %>
    </ol>
  <% end %>

  <%= tag.div id: "top-3-cities-shipped" do %>
    <h4>Top 3 Cities where Orders Ship</h4>
    <ol>
    <% @top_3_cities.each do |order| %>
    <%= tag.li class: 'city' do %>
    <%= order.city %> <%= order.state %>, <%= pluralize(order.order_count, 'order') %>
    <% end %>
    <% end unless @top_3_cities.nil? %>
    </ol>
  <% end %>

  <%= tag.div id: "top-3-quantity-orders" do %>
    <h4>Top 3 Orders with Most Item Quantity</h4>
    <ol>
    <% @top_3_quantity_orders.each do |order| %>
    <%= tag.li class: 'order' do %>
    <%= order.user_name %> bought <%= order.total_quantity %> items in one order
    <% end %>
    <% end unless @top_3_quantity_orders.nil? %>
    </ol>
  <% end %>
  <%= tag.div id: "total-sold" do %>
    <h4>Total Sold by all Merchants in completed orders.</h4>
    <%= tag.div id: 'bar-chart-group' do %>
      <p>Total Sales: <%= @total_sales[:tas] %></p>
      <%= render partial: "merchants/pie_chart", locals: {total_data: @total_sales[:tbm], qsp_data: {}} %>
    <% end %>
  <% end %>
<% end %>

app/views/merchants/show.html.erb
<h2>Merchant Dashboard for <%= @merchant.name %></h2>

<%= tag.div class: 'profile' do %>
  <p><%= @merchant.email %></p>
  <%= tag.div id: 'address' do %>
    <p><%= @merchant.address %><br/>
    <%= @merchant.city %>, <%= @merchant.state %> <%= @merchant.zip %></p>
  <% end %>
<% end %>

<% if current_admin? %>
<%= link_to 'My Items', admin_merchant_items_path(@merchant) %>
<% else %>
<%= link_to 'My Items', dashboard_items_path %>
<% end %>

<% if current_admin? %>
<%= button_to "Downgrade to User", admin_merchant_downgrade_path(@merchant), method: :patch %>
<% end %>

<%= tag.div id: 'orders' do %>
  <% if @orders.empty? %>
    You don't have any pending orders to fulfill
  <% else %>
    <ul>
      <% @orders.each do |order| %>
        <%= tag.li id: "order-#{order.id}" do %>
          <%= render partial: "merchants/order_card", locals: {order: order} %>
        <% end %>
      <% end %>
    </ul>
  <% end %>
<% end %>

<%= tag.div id: 'statistics' do %>
  <%= tag.div id: 'top-5-items' do %>
    <h4>Top 5 items sold by quantity</h4>
    <ol>
    <% @top_5_items.each do |item| %>
    <%= tag.li class: 'item' do %>
    <%= item.name %>, quantity sold: <%= item.quantity_sold %>
    <% end %>
    <% end %>
    </ol>
  <% end %>

  <%= tag.div id: 'quantity-sold' do %>
    <h4>Items Shipped as Percentage of Inventory</h4>
    <p>You have sold <span class="sold-span"><%= @qsp[:sold] %></span> items out of <%= @qsp[:total] %> (<%= @qsp[:percentage] %>%)</p>

    <%= tag.div id: 'pie-chart-group' do %>
      <%= render partial: "merchants/pie_chart", locals: {qsp_data: @qsp, total_data: []} %>
    <% end %>
  <% end %>

  <%= tag.div id: 'monthly-sales' do %>
    <h4>Items sold per month</h4>
    <%= tag.div id: 'bar-chart-group' do %>
      <%= render partial: "merchants/bar_chart", locals: {chart_data: @monthly_sales} %>
    <% end %>
  <% end %>

  <%= tag.div id: 'top-3-states' do %>
    <h4>Top 3 States where Items were Shipped</h4>
    <ol>
    <% @top_3_states.each do |order| %>
    <%= tag.li class: 'state' do %>
    <%= order.state %>, quantity shipped: <%= order.quantity_shipped %>
    <% end %>
    <% end %>
    </ol>
  <% end %>

  <%= tag.div id: 'top-3-cities' do %>
    <h4>Top 3 Cities where Items were Shipped</h4>
    <ol>
    <% @top_3_cities.each do |order| %>
    <%= tag.li class: 'city' do %>
    <%= order.city %>, <%= order.state %>, quantity shipped: <%= order.quantity_shipped %>
    <% end %>
    <% end %>
    </ol>
  <% end %>

  <%= tag.div id: 'most-ordering-user' do %>
    <h4>User with most orders</h4>
    <% if @most_ordering_user.nil? %>
    <p>You don't have any orders yet</p>
    <% else %>
    <p><%= @most_ordering_user.name %>, with <%= @most_ordering_user.order_count %> orders</p>
    <% end %>
  <% end %>

  <%= tag.div id: 'most-items-user' do %>
    <h4>User with most items bought</h4>
    <% if @most_items_user.nil? %>
    <p>You don't have any orders yet</p>
    <% else %>
    <p><%= @most_items_user.name %>, with <%= @most_items_user.item_count %> items</p>
    <% end %>
  <% end %>

  <%= tag.div id: 'top-3-revenue-users' do %>
    <h4>Top 3 Users by Revenue</h4>
    <ol>
    <% @top_3_revenue_users.each do |user| %>
    <%= tag.li class: 'user' do %>
    <%= user.name %>, revenue: <%= number_to_currency(user.revenue) %>
    <% end %>
    <% end %>
    </ol>
  <% end %>
<% end %>