config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :items, only: [:index, :show], param: :slug
  resources :merchants, only: [:index]

  get '/cart', to: 'cart#index'
  post '/cart/additem/:slug', to: 'cart#add_item', as: 'cart_add_item'
  post '/cart/addmoreitem/:slug', to: 'cart#add_more_item', as: 'cart_add_more_item'
  delete '/cart', to: 'cart#destroy', as: 'cart_empty'
  delete '/cart/item/:slug', to: 'cart#remove_more_item', as: 'cart_remove_more_item'
  delete '/cart/item/:slug/all', to: 'cart#remove_all_of_item', as: 'cart_remove_item_all'

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  get '/logout', to: 'session#destroy'

  get '/register', to: 'users#new', as: 'registration'
  resources :users, only: [:create, :update], param: :slug

  get '/dashboard', to: 'merchants#show', as: 'dashboard'
  namespace :dashboard do
    resources :orders, only: [:show] do
      patch '/items/:slug/fulfill', to: 'orders#fulfill_item', as: 'item_fulfill'
    end
    resources :items, except: [:show], param: :slug
    patch '/items/:slug/enable', to: 'items#enable', as: 'enable_item'
    patch '/items/:slug/disable', to: 'items#disable', as: 'disable_item'
  end
  get '/profile', to: 'profile#index', as: 'profile'

  get '/profile/edit', to: 'users#edit'
  namespace :profile do
    resources :orders, only: [:index, :create, :show, :destroy]
  end

  get '/admin/users/:merchant_slug/items', to: 'admin/items#index', as: 'admin_merchant_items', param: :slug
  post '/admin/users/:merchant_id/items', to: 'dashboard/items#create', as: 'admin_user_items'
  patch '/admin/users/:merchant_id/items/:slug', to: 'dashboard/items#update', as: 'admin_user_item'
  namespace :admin do
    resources :users, only: [:index, :show, :edit], param: :slug do
      patch '/enable', to: 'users#enable', as: 'enable'
      patch '/disable', to: 'users#disable', as: 'disable'
      patch '/upgrade', to: 'users#upgrade', as: 'upgrade'
      resources :orders, only: [:index, :show]
    end
    resources :merchants, only: [:show], param: :slug do
      patch '/enable', to: 'merchants#enable', as: 'enable'
      patch '/disable', to: 'merchants#disable', as: 'disable'
      patch '/upgrade', to: 'merchants#downgrade', as: 'downgrade'
      resources :items, only: [:new, :edit], param: :slug
    end
    resources :dashboard, only: [:index]
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %>
          <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
        <%= link_to 'Items', items_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Merchants', merchants_path, class: 'nav-link' %>
      </li>
      <% if current_user.nil? || current_user.default? %>
      <li class="nav-item">
        <%= link_to "Cart: #{@cart.total_count}", cart_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
    <ul class="navbar-nav mr-auto navbar-right">
    <% if current_user.nil? %>
      <li class="nav-item"><%= link_to 'Log in', login_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Register', registration_path, class: 'nav-link' %></li>
    <% else %>
      <li class="nav-item"><a class="nav-link disabled">Logged in as <%= current_user.name %></a></li>
      <% if current_user.default? %>
      <li class="nav-item"><%= link_to 'Profile', profile_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Orders', profile_orders_path, class: 'nav-link' %></li>
      <% end %>
      <% if current_user.merchant? %>
      <li class="nav-item"><%= link_to 'Dashboard', dashboard_path, class: 'nav-link' %></li>
      <% end %>

      <% if current_admin? %>
      <li class="nav-item"><%= link_to 'Users', admin_users_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'Dashboard', admin_dashboard_index_path, class: 'nav-link' %></li>
      <% end %>

      <li class="nav-item"><%= link_to 'Log out', logout_path, class: 'nav-link' %></li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LittleShopBaseSmall</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>

    <div class="container" id="body-content-no-nav">
      <% flash.each do |flash_type, flash_message| %>
      <div class="alert alert-<%= flash_type %>" role="alert"><%= flash_message %></div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>